name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          php_version: 7.4

  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.1']
        composer-args: ['--prefer-stable', '--prefer-lowest', '']
        composer-command: ['install', 'update']
        exclude:
          - composer-args: '--prefer-stable'
            composer-command: 'install'
          - composer-args: '--prefer-lowest'
            composer-command: 'install'
          - composer-args: ''
            composer-command: 'update'

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-versions }}
          command: ${{ matrix.composer-command }}
          args: ${{ matrix.composer-args }}
      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml
          php_version: ${{ matrix.php-versions }}
